### ISSUE TITLE
Bootstrap pagefault when clock and shell are both set and ModuleAlign is set

### ISSUE THREAD

**Issue by roblabla** [roblabla42/KFS#12] opened 2018-10-19 17:22 UTC
557ac044c5932a6e2c138a9f4ccf2a463adaa11c

**Comment by Orycterope** [comment] 2018-11-15 23:36
Was caused by bootstrap not identity-mapping enough memory. Fixed in b95f0c02943c946ca472c27dc14616561051c000

**Closed** 2018-11-15 23:36 UTC
